# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rob', '0002_auto_20170202_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='games',
        ),
    ]
