# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rob', '0004_game_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_no',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='selection',
            unique_together=set([('game', 'player')]),
        ),
    ]
