# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rob', '0009_game_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='viewable',
            field=models.BooleanField(default=True),
        ),
    ]
