# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rob', '0010_selection_viewable'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='credits',
            field=models.IntegerField(blank=True, default=10),
        ),
    ]
