# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rob', '0011_player_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pot',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
