# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rob', '0012_game_pot'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='stake',
            field=models.IntegerField(blank=True, default=True),
        ),
    ]
