# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 18:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rob', '0013_selection_stake'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='previous_colours',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=100, null=True), default=[], size=None),
            preserve_default=False,
        ),
    ]
