# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rob', '0020_auto_20170205_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='lost_round',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
