# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rob', '0021_auto_20170205_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selection',
            name='lost_round',
        ),
    ]
